#!/usr/bin/env bash
set -e
# Ear-marked to mv to @telicent-oss/telicent-frontend-cli
# Check if the container exists and remove it if it does
if [ "$(docker ps -a -q -f name=telicent-access-ui-local-running)" ]; then
    docker rm -f telicent-access-ui-local-running
fi

docker images | grep telicent-access-ui-local

# Run the Docker container
docker run -p 8080:80 --name telicent-access-ui-local-running telicent-access-ui-local

