#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd frontend
if grep -Fq 'npm.fontawesome' yarn.lock; then
  echo '✗ Forbidden private registry "npm.fontawesome" found in yarn.lock. This may have snuck in via `.npmrc` or perhaps `yarn link`' >&2
  exit 1
fi
cd -