name: Build and push telicent-access

on:
  # Manually execute
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md

  #add dispatch in case job fails and needs to be manually executed
  workflow_dispatch:

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version from package.json
        id: semver
        uses: martinbeentjes/npm-get-version-action@main
    outputs:
      version: ${{ steps.semver.outputs.current-version }}

  integrated_tests:
    permissions:
      id-token: write
      contents: read
      packages: write
    needs: get_version
    env:
      APP_NAME: access
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: configure-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Get node version
        id: node
        run: |
          echo "version=$(node -v)" >> $GITHUB_OUTPUT

      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: cd frontend && mkdir reports && LOCAL_MACHINE=false yarn install
      - run: cd frontend && yarn test:ci

  vuln_scan_api:
    needs:
      - get_version
      - integrated_tests
    uses: telicent-oss/shared-workflows/.github/workflows/vulnerability-scanning-on-repo.yml@update/for-frontend-trivy
    with:
      APP_NAME: access
    secrets: inherit

  vuln_scan_frontend:
    needs:
      - get_version
      - integrated_tests
    uses: telicent-oss/shared-workflows/.github/workflows/vulnerability-scanning-on-repo.yml@update/for-frontend-trivy
    with:
      APP_NAME: access
      package-directory: frontend
    secrets: inherit

  publish_frontend:
    needs:
      - integrated_tests
      - get_version
      - vuln_scan_frontend
    uses: telicent-oss/shared-workflows/.github/workflows/docker-push-to-registries.yml@update/for-frontend-trivy
    with:
      APP_NAME: access
      DOCKERFILE: Dockerfile
      PATH: ./frontend
      VERSION: ${{ needs.get_version.outputs.version }}
      ALLOW_MUTABLE_TAGS: false
      package-directory: frontend
      DRY_RUN: true
    secrets: inherit
  publish_api:
    needs:
      - integrated_tests
      - get_version
      - vuln_scan_api
    uses: telicent-oss/shared-workflows/.github/workflows/docker-push-to-registries.yml@update/for-frontend-trivy
    with:
      APP_NAME: access-api
      DOCKERFILE: Dockerfile
      VERSION: ${{ needs.get_version.outputs.version }}
      ALLOW_MUTABLE_TAGS: false
    secrets: inherit
